language: java

jdk:
  - openjdk15

sudo: false

env:
  global:
    - CODECOV_TOKEN=53e25657-876e-4ec7-9cb7-948167dfffdf

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - asultangareev@gmail.com
    on_success: never # default: change
    on_failure: always # default: always